name: Great Learning Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        run: pip install -r requirements.txt
